### ISSUE TITLE
triggers plugin: can't reassign keyboard shortcut if target file is missing

### ISSUE THREAD

**Issue by veksha** [kupferlauncher/kupfer#174]
i have set shortcut to application "ctrl+alt+c"
but now that app is removed.
now i can't assign "ctrl+alt+c" to another app.

i suppose i need to install that old app again and remove trigger and then i can assign it to a new app.

### Environment

Kupfer Version:v321
Window Manager: qtile
Desktop Environment:
Linux Distribution:void linux

### Actual Behaviour

can't assign trigger that was assigned to old app which is gone now.

### Expected Behaviour

Kupfer should allow reassigning trigger to another app automatically removing trigger from old app.

**Comment by KarolBedkowski** [comment]
Current triggers can be viewed and removed - they are under "Triggers" leaf.

As long trigger may be assigned to almost any action (not only to application) is very hard to detect is current trigger is invalid. Also binding is handled by keybinder and simply you can't press the same key sequence because this is blocked on higher level.
