### ISSUE TITLE
text/uri-list from clipboard become default select

### ISSUE THREAD

**Issue by sfischme** [kupferlauncher/kupfer#54]
When marking files in a file manager for copying (Ctrl-C), it creates multi-part mime type (text/uri-list and text/plain). It would be great if there were an option that any files in text/uri-list would become the default selection when launching kupfer.

The use of it is to mark a couple of files for copying and then pipe them into an action in kupfer. Tke a look here at 1:05 https://www.youtube.com/watch?v=xfJHYX7venM

Steps:

1. open thunar
2. select a file
3. press Ctrl-C
4. launch kupfer

### Environment

Kupfer Version: kupfer v311-4-gd8a469d4
Window Manager: i3
Desktop Environment: none
Linux Distribution: archlinux

### Actual Behaviour

kupfer launched as normal

### Expected Behaviour

kupfer launched with the files select and the focus is on the action box.

**Comment by SanskritFritz** [comment]
I was about to answer "just use the Show with Selection" shortcut, but as I tried that, here it doesn't even work. But that should be another bug report probably.

**Comment by bluss** [comment]
Yes. File manager integration was kind of the holy grail. Back in the good old days there was a plugin to nautilus that broadcasted its selected files over d-bus, and a Selected File proxy object that used that. That idea should come back.

For Thunar I have documented what I use, like this: https://kupferlauncher.github.io/help/en/plugin-thunar.html  I think that works well and Thunar is the best integrated file manager, since it has a nice D-Bus API so that we can have Select in File Manager, Copy File using Thunar's progress window and so on.

- kupfer launched with the files select and the focus is on the action box.

I have wondered about this. I think this is a change we should consider in several places, for example, when selecting the result of an action? When dropping or pasting files?

**Comment by bluss** [comment]
btw, xfdesktop doesn't put text/uri-list on the clipboard when copying. That's inconsistent with thunar.

**Comment by SanskritFritz** [comment]
I'll open a separate bug report then.

**Comment by bluss** [comment]
Ok. A new global shortcut for show with clipboard seems fine then?

**Comment by bluss** [comment]
By the way, Kupfer has a major bug. I can't find the way to put uri list on the clipboard in Gtk. Meaning that files → copy to clipboard is broken, only copies it as text.

**Comment by bluss** [comment]
Come to think about it, you canmake your own show with X for any proxy object. Use select in kupfer from higher order actions and a trigger.

**Comment by bluss** [comment]
I have decided to close the issue of shortcut for a clipboard file: Kupfer already has this feature.

Enable: Higher order actions, Clipboard and Trigger plugins.

Combine Clipboard File, Select In Kupfer, Ctrl + Return to build command object and add a trigger.

Selecting the action pane by default after this is a separate bug.

**Comment by bluss** [comment]
Focus action is issue #57

**Comment by bluss** [comment]
Only tangentially related, but it's a start:

Kupfer v312 has new accelerators in the interface (no setting for them by default, I'll try them out and pick something later).

- Select Cliboard File, Select Cliboard Text,
- Select Pane {1, 2, 3}

So that's another way to do it. It's independent of triggers and global keybinds which are have an uncertain future (wayland and other future tech will obsolete current global keybinding code).
