### ISSUE TITLE
GTG: Clear up Dismiss vs Postponed

### ISSUE THREAD

**Issue by bluss** [kupferlauncher/kupfer#60]
GTG version: 0.3.1
Kupfer version: 312

Current behaviour and names of actions like dismiss/postpone in the plugin do not seem to be consistent with the gtg app.

cc @khurshid-alam Input welcome.

**Comment by khurshid-alam** [comment]
Postponed has deprecated long ago. It simply doesn't work in 3.1.

Dismiss simply discards the task it doesn't have to be accomplished. Dismissed and Accomplished, bot tasks appear in closed tasked pane. User can revert it from there. You can open `~/.local/share/gtg/gtg_tasks.xml `and monitor task status when a task gets dismissed,

The current behavior of kupfer plugin is wrong. It should set task status to "Dismiss". Otherwise task disappears completely from gui.

### Patch

```diff
class Dismiss (Action):
    def __init__(self):
        Action.__init__(self, _("Dismiss"))

    def activate(self, leaf):
-      _change_task_status(leaf.object, 'Postponed')
+      _change_task_status(leaf.object, 'Dismiss')

    def get_icon_name(self):
        return 'gtk-cancel'

**Comment by bluss** [comment]
Thanks for clearing that up. I'll set the accelerators correctly then too, when this is clear.
