### ISSUE TITLE
Idea: Actions in the Primary Pane

### ISSUE THREAD

**Issue by bluss** [kupferlauncher/kupfer#77]
One idea that is at the back of my mind is to allow certain actions to be found in the primary pane. When an action is selected in the primary pane, the action pane is hidden and the third (indirect object) pane is shown to select object to act upon.

One example of a sensible action to “reverse” in this way would be *Write Email To → (Contact)*

**Comment by khurshid-alam** [comment]
Interesting idea.

**Comment by khurshid-alam** [comment]
Any example for this ?

**Comment by bluss** [comment]
On example is *Write Email To → (Contact)*

**Comment by bluss** [comment]
If we can't make this work predictably and well, we will not do it. It's of course important that features in Kupfer work predictably and that what works with one action continues to work with another. In that sense this one is a bit risky.

Is this a good idea for  *Play Song → (Song)* for example?  Or *Create Archive → (Files)* ?

**Comment by khurshid-alam** [comment]
> Is this a good idea for Play Song → (Song) for example? Or Create Archive → (Files) ?
No. But it may be useful for some type of actions:

1. git status → Local Project Repo (folders)

2. weather → Place

3. Send tweet or DM  → Contact (Because we don't really remember contacts for twitter)

4. Sock price → Stock/Exchange or Notification

5. Today → aggregation of all calendar events and tasks for today
