### ISSUE TITLE
CTRL+C should be the default accelerator for Copy (Clipboard) ?

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#80]
### Actual Behaviour

1. Search for any previous clipboard item.

2. Press `CTRL+C`, it will copy the object but kupfer window will remain on the screen as if it is expecting to perform an action even though it has already performed `copy` action.

### Expected Behavior
CTRL+C is available as default accelerator for **copy**. 

After pressing CTRL+C, kupfer copy the object and vanishes.

I would be nice if we can have CTRL+C as default accelerator for copy. I can manually set it from preference but it also adds an extra step after each re-installation.

**Comment by bluss** [comment]
Ctrl + C already copies though, I hadn't considered the go away vs no go away behaviour. I do think it's best to keep the native ctrl + c instead of delegating to the action.

**Comment by khurshid-alam** [comment]
> I do think it's best to keep the native ctrl + c instead of delegating to the action.

Both do the same thing here. No?

**Comment by bluss** [comment]
Programmers need to master corner cases. Found it when challenged :wink:

In free text mode, native Ctrl + C is needed so that it copies just the part of the text that is selected. So we can't implement this by just adding a default accel for Copy (to Clipboard).

(On this topic: It is regrettable that in Python + Gtk 3 we can't set uri-list [files] on the clipboard!)

**Comment by khurshid-alam** [comment]
Ok. Yes in free text mode native copy is used. Closing this.
