### ISSUE TITLE
Bug: KDE -> Kupfer window opening position.

### ISSUE THREAD

**Issue by Grogglex** [kupferlauncher/kupfer#87]
Please provide enough information to reproduce the issue.

On KDE Kupfer seems to open is strange/random spots on the screen rather than the center or the last remembered position.

### Environment

Kupfer Version: 319
Window Manager: Kwin
Desktop Environment: KDE 
Linux Distribution: Manjaro

### Actual Behaviour
Kupfer window opens up in a random spot on the screen when the shortcut key is pressed (usually on an edge).

### Expected Behaviour
Kupfer window opens where it was last dragged when shortcut key is pressed.

**Comment by bluss** [comment]
Is this using wayland?

**Comment by Grogglex** [comment]
No, just plasma.

**Comment by SanskritFritz** [comment]
This is KDE feature. Actually the same happens in Openbox as well. You can make KDE remember Kupfer's position in Special Window Settings.

**Comment by bluss** [comment]
Kupfer could also change what it tells the WM.

You can experiment with setting `KUPFER_WINDOW_POSITION=CENTER` or `CENTER_ALWAYS` when starting kupfer.

If you report back that it behaves better with any of those two, then that increases the chances we change the default. I can't really experiment so much with window placement and monitor placement, because there are so many configurations to test.. I don't want to break those that already work.

For example, using xfwm4, kupfer behaves best and stays where the user puts the window if window position is not set.

**Comment by Grogglex** [comment]
Is there a place to set that in Kupfer's config itself? I can use it as an environment variable, but I'm just curious.

**Comment by bluss** [comment]
There isn't, they are there for troubleshooting (KUPFER_WINDOW_TYPE_HINT). They were recently added to debug issues like this, the idea to not commit to anything before we know more. If it's something that users need to set, then we should make it a config.

**Comment by Grogglex** [comment]
Issue Resolved.

**Comment by bluss** [comment]
Cool, and thanks for reporting back that it worked.
